version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-tiktok-data}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "27017:27017"

  frontend:
    image: hecatechvn/tiktok-web:latest
    build:
      context: ./tiktok-web
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=${FRONTEND_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-dev-nextauth-secret-key}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000/api/v1}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: hecatechvn/nest-tiktok:latest
    build:
      context: ./NestTiktok
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${BACKEND_PORT:-8000}
      - MONGO_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-admin123}@mongodb:27017/${MONGO_DATABASE:-tiktok-data}?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-dev-jwt-secret-key}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION:-15m}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-7d}
      - API_PREFIX=${API_PREFIX:-api}
      - API_VERSION=${API_VERSION:-1}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  mongodb_config: 