export enum Role {
  ADMIN = 'admin',
  USER = 'user',
}

export enum GRANT_TYPE {
  AUTHORIZED_CODE = 'authorized_code',
  REFRESH_TOKEN = 'refresh_token',
}

export enum CancellationInitiator {
  BUYER = 'BUYER',
  SELLER = 'SELLER',
  SYSTEM = 'SYSTEM',
}

export enum OrderStatus {
  UNPAID = 'UNPAID',
  ONHOLD = 'ON_HOLD',
  AWAITING_SHIPMENT = 'AWAITING_SHIPMENT',
  PARTIALLY_SHIPPING = 'PARTIALLY_SHIPPING',
  AWAITING_COLLECTION = 'AWAITING_COLLECTION',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
}

export enum FulfillmentType {
  FULFILLMENT_BY_DILAYANI_TOKOPEDIA = 'FULFILLMENT_BY_DILAYANI_TOKOPEDIA',
  FULFILLMENT_BY_SELLER = 'FULFILLMENT_BY_SELLER',
  FULFILLMENT_BY_TIKTOK = 'FULFILLMENT_BY_TIKTOK',
}

export enum DeliveryType {
  HOME_DELIVERY = 'HOME_DELIVERY',
  COLLECTION_POINT = 'COLLECTION_POINT',
}
